### ISSUE TITLE
Конфигурация модулей

### ISSUE THREAD

**Issue by loveorigami** [HaruAtari/yii2-module-app#1]
Спасибо за интересную статью. Жду продолжения ).
При чтении возник вопрос:
- Модули мы подключили с нужной версией. 
А как дела обстоят с конфигурированием модуля? раз уж мы подключаем через базу, то логичнее хранить настройки там. Но иногда нужно в конфиге задать параметр через аноноимку или целый массив... Может смержить нужно будет сначала глобальные, а потом локальные настройки... и закешировать.

Как наиболее оптимально решить такую ситуацию?

У себя я делаю так
https://github.com/loveorigami/lo-module-love/blob/master/ModuleConfig.php
и подкдючаю эти настройки вручную...

Насчет роутеров - тут еще не маловажен и порядок их подключения...
если в модуле (условно Page) мы хотим получить короткие url типа site.com/about
создаем правило
```
    'components'=>[
        'urlManager'=>[
            'rules'=>[
                ['pattern'=>'<slug>', 'route'=>'content/page/view']
            ]
        ]
    ]
```
и загрузим этот модуль первым, то перестанут работать правила из других модулей.
Например
https://github.com/loveorigami/lo-module-love/blob/master/config/main.php
```
return [
    'modules' => [
        'love' => [
            'class' => 'lo\modules\love\Module',
        ],
    ],
    'components'=>[
        'urlManager'=>[
            'rules'=>[
                'aphorism/<slug:[\w\-]+>' => 'love/aphorism/view',
                'aphorism' => 'love/aphorism/index',
            ]
        ]
    ]
];
```
Видимо, нужно в модель модулей внести сортировку и загружать по ней?

**Comment by HaruAtari** [comment]
Спасибо за интерес к теме.

По поводу конфигов не совсем понял о чем речь? Если вы говорите о полях самого модуля, то значения для них указываются в самом классе. Что-то вроде этого:
```php
class ExampleModule extends Module {
    public $someParam = 'value';
}
```
Если нужно запихать туда не скалярное значение, то можно назначить его в `init()` методе.

В конфиг же самого приложения модуль лезть не должен - приложение конфигурируется только на уровне ядра. Если модуль будет менять глобальные настройки, то появляется неявная зависимость от него. В таком случае при его включении/отключении может измениться работа других модулей, а это неприемлемо. Модуль может зависеть от ядра, но не менять его.


По поводу роутов. Как я упоминал в статье, я рассказывал в контексте REST сервера. Там структура url-а обычно отражает структуру модулей. Т.е. в урле фигурирует id модуля. Префикс можно указывать в урле вручную (я предпочитаю делать так), а можно сделать это автоматически, добавив соответствующую логику в `\app\components\UrlManager::registerModuleRules()`.

Но если вы считаете, что роуты одного модуля могут затирать модули роуты другого, то вам, конечно же, надо будет позаботится о порядке их подключения. Сортировать таблицу с модулями, как вы предложили, - хорошее решение. Тем более, что вам это скорее всего понадобится и для других целей (в той же админке их выводить).

Здесь лежит минимально необходимый каркас. Очень много всего вырезано, чтобы не захламлять код. Недостающие фичи всегда можно добавить в конкретном проекте - нет смысла тянуть их в базовый каркас.

**Comment by loveorigami** [comment]
Спасибо за разъяснение по конфигу. Подумаю под таким подходом у себя в проекте.

**Comment by HaruAtari** [comment]
Пожалуйста!
